# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

defaults: &defaults
  github_access_token: <%= ENV["CODY_GITHUB_ACCESS_TOKEN"] %>
  github_integration_identifier: <%= ENV["CODY_GITHUB_INTEGRATION_IDENTIFIER"] %>
  github_integration_client_id: <%= ENV["CODY_GITHUB_INTEGRATION_CLIENT_ID"] %>
  github_integration_client_secret: <%= ENV["CODY_GITHUB_INTEGRATION_CLIENT_SECRET"] %>

development:
  <<: *defaults
  secret_key_base: d960fb992f78c433b9842d0ff2c79fc2e8443d5c2e50c7fb89423efb2890d3ae458009f276bdad9b9874cfefe5d42778125459a3af3a7da48f853f885befaa59

test:
  <<: *defaults
  secret_key_base: 99cf42377af48fc145dcc904541076138c76d3bfa5d3af10c10f62f056466b94a4dcca1f4b5f191eb6ecd04d3010d956b1223941c2938102350fced4f9cbf864

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
